apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsstarter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsstarter-api
  template:
    metadata:
      labels:
        app: devopsstarter-api
    spec:
      containers:
        - name: api
          image: ghcr.io/einaltesfeh1657136135-ui/devopsstarter-api@sha256:ec8805000de0d137399928abdfb9180fa789b871d714a7619d3e5326d25db314
          ports:
            - containerPort: 8080
          env:
            - name: App__Environment
              value: "Production"
